services:
  Civi\Mascode\FormProcessor\Action\ExampleFormAction:
    tags:
      - { name: form_processor_action }
    public: true

  Civi\Mascode\CiviRules\Action\ExampleCiviRulesAction:
    tags:
      - { name: civirules_action }
    public: true

  Civi\Mascode\CiviRules\Action\ServiceRequestToProject:
    tags:
      - { name: civirules_action }
    public: true

  Civi\Mascode\Event\CasePreInsertListener:
    tags:
      - { name: "civicrm.hook_subscriber" }
    public: true
