<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from mascode/xml/schema/CRM/Mascode/MascodeSubmission.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:6e75f856b38b32beb9f22c6b46ba8180)
 */

use CRM_Mascode_ExtensionUtil as E;

/**
 * Database access object for the MascodeSubmission entity.
 */
class CRM_Mascode_DAO_MascodeSubmission extends CRM_Core_DAO
{
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_mascode_submission';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique MascodeSubmission ID
   *
   * @var int|string|null
   */
  public $id;

  /**
   * FK to Organization Contact
   *
   * @var int|string|null
   */
  public $organization_contact_id;

  /**
   * FK to Contact 2
   *
   * @var int|string|null
   */
  public $contact_id_2;

  /**
   * FK to Contact 3
   *
   * @var int|string|null
   */
  public $contact_id_3;

  /**
   * Submission date
   *
   * @var string|null
   */
  public $submission_date;

  /**
   * ID of the form that was submitted
   *
   * @var string|null
   */
  public $form_id;

  /**
   * JSON array of field name-value pairs
   *
   * @var string|null
   */
  public $field_data;

  /**
   * Current status of the form submission
   *
   * @var string|null
   */
  public $status;

  /**
   * Class constructor.
   */
  public function __construct()
  {
    $this->__table = 'civicrm_mascode_submission';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE)
  {
    return $plural ? E::ts('Mascode Submissions') : E::ts('Mascode Submission');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields()
  {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => ['name' => 'id', 'type' => CRM_Utils_Type::T_INT, 'title' => E::ts('ID'), 'required' => TRUE],
        'organization_contact_id' => ['name' => 'organization_contact_id', 'type' => CRM_Utils_Type::T_INT, 'title' => E::ts('Organization Contact ID'), 'FKClassName' => 'CRM_Contact_DAO_Contact'],
        'contact_id_2' => ['name' => 'contact_id_2', 'type' => CRM_Utils_Type::T_INT, 'title' => E::ts('Contact ID 2'), 'FKClassName' => 'CRM_Contact_DAO_Contact'],
        'contact_id_3' => ['name' => 'contact_id_3', 'type' => CRM_Utils_Type::T_INT, 'title' => E::ts('Contact ID 3'), 'FKClassName' => 'CRM_Contact_DAO_Contact'],
        'submission_date' => ['name' => 'submission_date', 'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME, 'title' => E::ts('Submission Date'), 'default' => 'CURRENT_TIMESTAMP'],
        'form_id' => ['name' => 'form_id', 'type' => CRM_Utils_Type::T_STRING, 'title' => E::ts('Form ID')],
        'field_data' => ['name' => 'field_data', 'type' => CRM_Utils_Type::T_TEXT, 'title' => E::ts('Field Data')],
        'status' => ['name' => 'status', 'type' => CRM_Utils_Type::T_STRING, 'title' => E::ts('Status'), 'enumValues' => ['Pending', 'Approved', 'Spam', 'Rejected'], 'default' => 'Pending'],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE)
  {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'mascode_submission', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE)
  {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'mascode_submission', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE)
  {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }
}
