-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_mascode_submission`;

SET FOREIGN_KEY_CHECKS=1;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_mascode_submission
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mascode_submission` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique MascodeSubmission ID',
  `organization_contact_id` int unsigned COMMENT 'FK to Organization Contact',
  `contact_id_2` int unsigned COMMENT 'FK to Contact 2',
  `contact_id_3` int unsigned COMMENT 'FK to Contact 3',
  `submission_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Autogenerated when the row was added',
  `form_id` varchar(255) COMMENT 'ID of the form that was submitted',
  `field_data` text COMMENT 'JSON array of field name-value pairs',
  `status` enum('Pending', 'Approved', 'Spam', 'Rejected') DEFAULT 'Pending' COMMENT 'Current status of the form submission',

  PRIMARY KEY (`id`),

  CONSTRAINT `FK_civicrm_mascode_submission_organization_contact_id`
    FOREIGN KEY (`organization_contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,

  CONSTRAINT `FK_civicrm_mascode_submission_contact_id_2`
    FOREIGN KEY (`contact_id_2`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,

  CONSTRAINT `FK_civicrm_mascode_submission_contact_id_3`
    FOREIGN KEY (`contact_id_3`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

